// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://next.materialkolor.com/t/AWZewikEMhALQnVybnQgRW1iZXIn

package dev.gavenda.kozeki.ui.theme

import androidx.compose.ui.graphics.Color

val SeedColor = Color(0xFF665EC2)
